dist: trusty
language: python
python:
  - "2.7"
  - "3.6"

before_install:
 - sudo apt-get update -q
 - sudo apt-get install python-lxml gcc cmake libgeos++-dev libgdal-dev libsparsehash-dev libboost-dev libbz2-dev zlib1g-dev libexpat1-dev libutfcpp-dev libosmpbf-dev libprotobuf-dev protobuf-compiler cmake-curses-gui make libboost-python-dev
install:
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - pip install coveralls
 - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
 - git clone --quiet --depth 1 https://github.com/osmcode/pyosmium.git ../pyosmium
 - cd ../pyosmium
 - python setup.py build
 - python setup.py install
 - cd -
script:
 - PYTHONPATH="." coverage run test/test.py && coverage report
 - coveralls
