language: python
python:
  - "2.7"

install:
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - pip install coveralls
 - sudo apt-get install python-lxml
script:
 - PYTHONPATH="." coverage run test/test.py && coverage report
 - coveralls
