dist: trusty
language: python
services:
  - postgres
addons:
  postgresql: "9.4"
python:
  - "2.7"
  - "3.4"

before_install:
 - sudo apt-get update -q
install:
 - sudo apt-get install gettext python-lxml gcc cmake libgeos++-dev libgdal-dev libsparsehash-dev libboost-dev libbz2-dev zlib1g-dev libexpat1-dev libutfcpp-dev libosmpbf-dev libprotobuf-dev protobuf-compiler cmake-curses-gui
 - sudo apt-get install make libboost-python-dev
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - pip install coveralls
 - pip install osmium
before_script:
  - psql -c 'create database changewithin;' -U postgres -h localhost
  - psql -f changewithin/schema.sql -U postgres -h localhost -d changewithin
script:
 - pwd
 - ls
 - ./update_pot.sh
 - PYTHONPATH="." coverage run --include=changewithin/changewithin.py test/test.py && coverage report
 - coveralls